name: "Generic Script Runner"
description: |
  Specify the script content and the script runner
  binary and this step will execute it.

  The *runner* can even be a command, if it's available in the PATH
  and can execute the script it will work.

  For example to run a [Go](https://golang.org/) Hello ground "script"
  you can define the content:

      package main
      import "fmt"
      func main() {
          fmt.Println("hello ground")
      }

  Set the *Execute with* parameter to `go run` and specify
  a *script file path* because `go run` can only accept (at the moment)
  files with a .go extension (just specify `step.go` as the script path).

  If the `go` binary can be found in the PATH your Hello ground
  script will run without any problem.
website: https://github.com/bitrise-io/steps-generic-script-runner
fork_url: https://github.com/bitrise-io/steps-generic-script-runner
source:
  git: https://github.com/bitrise-io/steps-generic-script-runner.git
host_os_tags:
  - osx-10.10
project_type_tags: []
type_tags:
  - script
is_requires_admin_user: true
inputs:
  - 
    mapped_to: GENERIC_SCRIPT_RUNNER_CONTENT
    title: "Script content"
    description: |
      Type your script here.
    value: |
      #!/bin/bash

      echo "Hello Generic Script Runner!"
    is_expand: false
    is_required: true
  - 
    mapped_to: GENERIC_SCRIPT_RUNNER_BIN
    title: "Execute with"
    description: |
      The executor to be used for running the script.
      If it's available in the PATH you can just
      specify `ruby` or `python`, generally
      if you know the path of the executor you should
      define that, like `/bin/bash`.

      You can even specify an execution command
      like `go run` instead of just a binary.
    value: "/bin/bash"
    is_expand: false
    is_required: true
  -
    mapped_to: GENERIC_SCRIPT_RUNNER_WORKING_DIR
    title: "(optional) Working directory"
    description: |
      This directory will be set as the current working
      directory for the script.
    is_expand: true
    is_required: false
  -
    mapped_to: GENERIC_SCRIPT_RUNNER_SCRIPT_TMP_PATH
    title: "(optional) Script file path"
    description: |
      Save the specified script content to this path
      before execution. The file will be removed after
      the script finishes.

      Generally you don't have to define this but
      there might be cases where the file's name or path
      actually matters.
      For example `go run` only accepts .go files.

      If you specify a relative path then it will be
      relative to the *working directory* (which you
      can specify as well).
    is_expand: true
    is_required: false
